title: "Marc Andrés Carcasona"
description: "Astrophysicist | Gravitational Waves | Primordial Black Holes"
baseurl: ""               # keep empty for a user site
url: "https://marcandrescarcasona.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# --- the two lines that make the difference ---
include:                   # files Jekyll must render even though they’re in root
  - about.md

author:
  name   : "Marc Andrés Carcasona"
  avatar : "/assets/images/profile.jpg"
  bio    : "Postdoc at IFAE"
