title: "Marc Andrés Carcasona"
description: "Astrophysicist | Gravitational Waves | Primordial Black Holes"
url: "https://marcandrescarcasona.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
minimal_mistakes_skin: "neon"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

author:
  name   : "Marc Andrés Carcasona"
  avatar : "/assets/images/IMG_7073.JPG"
  bio    : "Postdoc at IFAE"

collections:
  pages:
    output: true
    permalink: /:path/

nav:
  - title: "About"
    url: /about/
