title: "Marc Andrés Carcasona"
description: "Astrophysicist | Gravitational Waves | Primordial Black Holes"
baseurl: ""               # keep empty for a user site
url: "https://marcandrescarcasona.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
sticky_header: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

include:
  - about.md
  - cv.md
  - publications.md

author:
  name   : "Marc Andrés Carcasona"
  avatar : "/assets/images/profile.jpg"
  bio    : "Postdoc at IFAE"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:mandres@ifae.es"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/AndresCarcasona"
