title: "Marc Andrés Carcasona"
description: "Astrophysicist | Gravitational Waves | Primordial Black Holes"
url: "https://marcandrescarcasona.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

author:
  name   : "Marc Andrés Carcasona"
  avatar : "/assets/images/profile.jpg"
  bio    : "Postdoc at IFAE"

nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
